<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BaseLib.Core\BaseLib.Core.csproj" />
    <ProjectReference Include="..\BasicErp.Inventory\BasicErp.Inventory.csproj" />
    <ProjectReference Include="..\BasicErp.Invoicing\BasicErp.Invoicing.csproj" />
    <ProjectReference Include="..\BasicErp.Shipping\BasicErp.Shipping.csproj" />
  </ItemGroup>
</Project>
